---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by acorn.
--- DateTime: 2024/10/13 16:45
---
local successList = KEYS[1]
local failedList = KEYS[2]
local startPos = tonumber(ARGV[1])
local endPos = tonumber(ARGV[2])
local successLen = tonumber(redis.call("LLEN", successList))
local failedLen = tonumber(redis.call("LLEN", failedList))
local nextStartPos = -1
if successLen <= startPos then
    local resp = redis.call("LRANGE", successList, startPos, endPos)
    for _, taskKey in ipairs(resp) do
        if redis.call("EXISTS", taskKey) == 0 then
            redis.call("LREM", successList, 1, taskKey)
        end
    end
    if endPos < successLen then
        nextStartPos = endPos+1
    end
end
if failedLen <= endPos then
    local resp = redis.call("LRANGE", failedList, startPos, endPos)
    for _, taskKey in ipairs(resp) do
        if redis.call("EXISTS", taskKey) == 0 then
            redis.call("LREM", failedList, 1, taskKey)
        end
    end
    if endPos < failedLen then
        nextStartPos = endPos+1
    end
end
return nextStartPos