---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by acorn.
--- DateTime: 2024/10/12 07:33
---

-- RetryTasks remove ts from active list and add tasks to retry sorted set conditional.
-- KEYS[1] -> asynq:{queueName}:retry
-- KEYS[2] -> asynq:{queueName}:active
-- KEYS[3..n] -> asynq:{queueName}:t:taskID
-- ARGV[1] -> retry state
-- ARGV[2..n] -> task start at unix timestamp seconds

local retry = KEYS[1]
local active = KEYS[2]
local retryState = ARGV[1]
for i = 2, #ARGV do
    local taskKey = KEYS[i + 1]
    local score = tonumber(ARGV[i])
    redis.call("ZADD", retry, score, taskKey)
    local retried = redis.call("JSON.GET", taskKey, "$.retried")
    if string.len(retried) > 2 then
        retried=tonumber(string.sub(retried,1,string.len(retried)-1))+1
        redis.call("JSON.MSET", taskKey, "$.state", retryState,taskKey,"$.retried",retried)
    end
    redis.call("LREM", active, 1, taskKey)
end
return redis.status_reply("OK")